from pathlib import Path
from typing import Union, Literal, Tuple, get_args
import re


filetypes = Literal["midi", "full_midi", "flac", "full_flac", "mp4",
                    "full_video", "video", "aac", "full_audio", "audio",
                    "trimmed_video"]

suffixes = Literal[".aac", ".flac", ".mp4", ".mid"]
suffixes_list: Tuple[suffixes, ...] = get_args(suffixes)


class PathUtils:
    """
    Contains various functions that help working with paths within the dataset.
    """

    def get_type(self, path: Path) -> filetypes:
        # TODO:
        # Instead of returning the filetype as a string, its much better
        # to return the list of tags the file has ("video", "full", "trimmed").
        if self.is_valid_midi(path):
            return "full_midi"
        elif self.is_valid_flac(path):
            return "full_flac"
        elif path.suffix == ".mp4":
            if self.is_trimmed(path):
                return "trimmed_video"
            if self.is_full_video(path):
                return "full_video"
            return "video"
        elif path.suffix == ".aac":
            if self.is_full_audio(path):
                return "full_audio"
            return "audio"

    @staticmethod
    def get_session_no(file: Path) -> Union[str, None]:
        """
        Get the session number from a given file in the format a01, a02, etc.
        """
        for i in file.stem.split("_"):
            if re.search(pattern="(^a|^v)\\d\\d$", string=i):
                return "a"+i[-2:]
        return None

    @staticmethod
    def get_date(file: Path) -> Union[str, None]:
        """
        Get the date from a given file in format yyyy_mm_dd.
        Raises an attribute error if a date cannot be found.
        """
        for i in file.stem.split("_"):
            if re.search(pattern="^\\d{4}-\\d{2}-\\d{2}$",
                         string=i):
                return i
        raise AttributeError("Date could not be identified from the given "
                             "file.")

    @staticmethod
    def is_full_audio(file: Path) -> bool:
        """
        Check whether a certain file is the full audio file as generated by
        extract_and_concat_audio.
        """

        return file.stem.split("_")[-1] == "full" and file.suffix == ".aac"

    @staticmethod
    def get_fileno_a(file: Path) -> int:
        """
        Get the file number for files using the a + 2 numbers format.
        """
        no = re.search(pattern="a\\d{2}", string=str(file)).group()
        return int(no[-2:])

    @staticmethod
    def get_fileno_p(file: Path) -> int:
        """
        Get the file number for files using the p + 3 numbers format.
        """
        no = re.search(pattern="p\\d{3}", string=str(file)).group()
        return int(no[-3:])

    @staticmethod
    def is_trimmed(file: Path) -> bool:
        """
        Check whether a file is a trimmed audio.
        """

        return file.stem.split("_")[-1] == "trimmed"

    @staticmethod
    def is_warmup(file: Path) -> bool:
        """
        Check if a file is from a warmup.
        """
        return file.stem.split("_")[0] == "warmup"

    @staticmethod
    def is_valid_flac(file: Path) -> bool:
        return file.suffix == ".flac" and file.stem.split("_")[-1][0] == "a"

    @staticmethod
    def is_valid_midi(file: Path) -> bool:
        """
        Check if a midi file is valid.
        """
        if not file.suffix == ".mid":
            return False
        return True

    @staticmethod
    def is_full_video(file: Path):
        """
        Check if a file is a full video file of a session
        """
        if file.suffix != ".mp4":
            return False

        split = file.stem.split("_")

        return split[-1] == "full"

    @staticmethod
    def get_files_by_type(root: Path,
                          filetype: Union[suffixes]) -> list[Path]:
        """
        Return all files in the dataset of a certain type. The types should be
        found in file_suffixes.

        Parameters
        ----------
        root: where to start the recursive search
        filetype: .mid, .flac, etc.

        Returns list of Path objects
        -------
        """
        files = [Path(j) for j in root.rglob('*' + filetype)]
        return files
